In [30]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__


'2.3.1'

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   engine_displacement  9704 non-null   int64  
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64  
 6   origin               9704 non-null   object 
 7   fuel_type            9704 non-null   object 
 8   drivetrain           9704 non-null   object 
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 834.1+ KB


In [5]:
df.shape

(9704, 11)

In [6]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [7]:
df['fuel_type'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 9704 entries, 0 to 9703
Series name: fuel_type
Non-Null Count  Dtype 
--------------  ----- 
9704 non-null   object
dtypes: object(1)
memory usage: 75.9+ KB


In [8]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max().round(2)

np.float64(23.76)

In [9]:
df['horsepower'].describe()

count    8996.000000
mean      149.657292
std        29.879555
min        37.000000
25%       130.000000
50%       149.000000
75%       170.000000
max       271.000000
Name: horsepower, dtype: float64

In [10]:
df['horsepower'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 9704 entries, 0 to 9703
Series name: horsepower
Non-Null Count  Dtype  
--------------  -----  
8996 non-null   float64
dtypes: float64(1)
memory usage: 75.9 KB


In [11]:
mean_horsepower = df['horsepower'].median()
mean_horsepower

np.float64(149.0)

In [12]:
mode_horsepower = df['horsepower'].mode()
mode_horsepower

0    152.0
Name: horsepower, dtype: float64

In [13]:
mode_horsepower = df['horsepower'].mode().iloc[0]
mode_horsepower

np.float64(152.0)

In [14]:
df['horsepower'] = df['horsepower'].fillna(mode_horsepower)

In [15]:
df['horsepower']

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [16]:
median_horsepower = df['horsepower'].median
mode_horsepower

np.float64(152.0)

In [17]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0       152.0     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [18]:
asia_cars_subset = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']]
asia_cars_subset.head(n=7)

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [19]:
X = asia_cars_subset.values
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       ...,
       [2545.07013932, 2012.        ],
       [3107.42781965, 2005.        ],
       [2908.04347736, 2005.        ]], shape=(3247, 2))

In [24]:
XT =X.T
XT 

array([[2714.21930965, 2783.86897424, 3582.68736772, ..., 2545.07013932,
        3107.42781965, 2908.04347736],
       [2016.        , 2010.        , 2007.        , ..., 2012.        ,
        2005.        , 2005.        ]], shape=(2, 3247))

In [25]:
XT.shape

(2, 3247)

In [23]:
X.shape

(3247, 2)

In [28]:
XTX = XT.dot(X)
XTX

array([[3.01651358e+10, 1.96349896e+10],
       [1.96349896e+10, 1.31377985e+10]])

In [32]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 1.21977675e-09, -1.82300740e-09],
       [-1.82300740e-09,  2.80067709e-09]])

In [33]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [34]:
XTX_inv.shape

(2, 2)

In [35]:
XT.shape

(2, 3247)

In [50]:
XTX_inv.dot(XT)

array([[-3.64441297e-07, -2.68546211e-07,  7.11302917e-07, ...,
        -5.63473493e-07,  1.35238384e-07, -1.07966002e-07],
       [ 6.98123134e-07,  5.54347218e-07, -9.10306654e-07, ...,
         9.95280615e-07, -4.95063361e-08,  3.13972795e-07]],
      shape=(2, 3247))

In [41]:
y.shape

(7,)